name: Feedback on Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
      - master  # Or trigger on 'master' branch

jobs:
  feedback-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version you are using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run JavaScript and CSS linters
      - name: Run ESLint for JavaScript
        run: |
          if [ -f ".eslintrc.json" ]; then
            npx eslint . || echo "❌ JavaScript linting failed. Please fix the issues."
          else
            echo "⚠️ ESLint configuration file not found. Skipping JavaScript linting."
          fi

      - name: Run Stylelint for CSS
        run: |
          if [ -f ".stylelintrc.json" ]; then
            npx stylelint "**/*.css" || echo "❌ CSS linting failed. Please fix the issues."
          else
            echo "⚠️ Stylelint configuration file not found. Skipping CSS linting."
          fi

      # Step 5: Provide feedback
      - name: Feedback summary
        run: |
          echo "✅ Feedback process complete. Check the Actions tab for details."
      
      # Optional: Post feedback as a comment
      - name: Post feedback comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request?.number || context.payload.after,
              body: "🚀 Feedback: Your push has been analyzed. Check the Actions tab for detailed feedback."
            })
